<?php

class ExampleTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->app->register(\App\SampleServiceProvider::class);
    }


    public function sampleData(){
        return [
            ["t.goto@chatbox-inc.com",["hoge"=>"piyo"]]
        ];
    }

    /**
     * @dataProvider sampleData
     */
    public function testExample($email,$data)
    {
        $this->post('/send',["email" => $email,"data"=>$data]);

        $this->assertResponseOk();
        $token = $this->response->getOriginalContent();
        $this->assertArrayHasKey("key",$token);
        $this->assertArrayHasKey("value",$token);

        $this->get('/check',["X-MAILTOKEN" => $token["key"]]);

        $this->assertResponseOk();
        $token = $this->response->getOriginalContent();

        $this->assertArrayHasKey("key",$token);
        $this->assertArrayHasKey("value",$token);
        $this->assertEquals(array_merge($data,["email"=>$email]),$token["value"]);

        $this->post('/handle',[],["X-MAILTOKEN" => $token["key"]]);
        $this->assertResponseOk();

        $this->get('/check',["X-MAILTOKEN" => $token["key"]]);

        $this->assertResponseStatus(500);
    }
}
